### PR TITLE
Except errors in build due to unimplemented features

### PR DESCRIPTION
**Pull request by AshleySetter**
fix errors raised when attempting to build and export examples directory manufacturers due to unimplemented features by trying and excepting failure, skipping files which do not build successfully and printing warning to terminal

### CODE REVIEW

**Review by cbrafter — APPROVED** [review]
Looks good

**Comment by aloisklink** [comment]
I think we might need to return an error exit code to bash, otherwise GitHub Actions CI might give a green tick, even when a build has failed due to invalid data.

Maybe it'd be easier to somehow ignore the `examples/` directory instead?

**Comment by AshleySetter** [comment]
> I think we might need to return an error exit code to bash, otherwise GitHub Actions CI might give a green tick, even when a build has failed due to invalid data.
> 
> Maybe it'd be easier to somehow ignore the `examples/` directory instead?

Good point, I'll add an optional flag for a debug mode which prints warnings and raise errors by default so that the CI doesn't allow failing yaml files past it.

**Comment by AshleySetter** [comment]
I've added a `--pass-on-failure` flag you can use to allow the validator to skip files failing due to missing files.

**Pull request merged**
